apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: experiment-argocd-deployment-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=gcr.io/firatkucuk/experiment-argocd
    argocd-image-updater.argoproj.io/myalias.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/firatkucuk/experiment-argocd.git
    targetRevision: HEAD
    path: infrastructure
  destination: 
    server: https://kubernetes.default.svc
    namespace: experiment-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
