name: Container Image Creation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: app
          push: true
          tags: ghcr.io/peel9/peel9:${{ env.BRANCH_NAME }}
