name: Container Image Creation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: app
          push: true
          tags: ghcr.io/firatkucuk/experiment-argocd:${{ env.SHORT_SHA }},ghcr.io/firatkucuk/experiment-argocd:latest
